apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nibbit-pebbles-flowise-cert
  namespace: istio-system
spec:
  # The secret name where cert-manager should store the signed certificate
  secretName: nibbit-pebbles-flowise-nibbit-ai-tls
  dnsNames:
    - flowise.pebbles.$(ENVIRONMENT)nibbit.ai
  # Duration of the certificate
  duration: 168h
  # Renew a day before the certificate expiration
  renewBefore: 24h
  # Reference the Origin CA Issuer you created above, which must be in the same namespace.
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: $(ENVIRONMENT)-issuer
